### PR TITLE
Higly Used Config Library - Cloth Config API

### PR DESCRIPTION
**Pull request by ibeticanhandlethis**
yes

### CODE REVIEW

**Comment by ibeticanhandlethis** [comment]
also i just do all changes in local git repo so it can be addition merges within that repo so

**Comment by ibeticanhandlethis** [comment]
like [0722ae7](https://github.com/nexia-cts/cts-mod-list/pull/2/commits/0722ae794cdc00405707ed73addb0c464ce7b892) one

**Comment by not-coded** [comment]
> also i just do all changes in local git repo so it can be addition merges within that repo so

fuck you, add more mods like cookeymod or smth@!@!

**Comment by ibeticanhandlethis** [comment]
> > also i just do all changes in local git repo so it can be addition merges within that repo so
> 
> fuck you, add more mods like cookeymod or smth@!@!

its before it so i can add mods with deps on them

**Comment by ibeticanhandlethis** [comment]
i wanna add autoreconnect (because server crashers), cookeymod and other things from minecraft combat update server

**Comment by ibeticanhandlethis** [comment]
this is dependency for autoreconnect

**Comment by ibeticanhandlethis** [comment]
just keeping everything organized

**Pull request merged**
